services:
  - type: web
    name: eduguard-api
    runtime: python

    # Se instala - actualiza las dependencias necesarias.
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    # Comando para el arranque de la app.
    startCommand: python main.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0 # VERSIÓN ESPECÍFICA DE PYTHON