#  configuración para Render que especifica el tipo de servicio, comandos de build y start.
services:
  - type: web
    name: eduguard-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_api.py
    envVars:
      - key: PORT
        value: 10000  # Render asignará dinámicamente, pero podemos especificar default